export const e2bJsonData = [
  { en: 'false', bn: 'ভুল, মিথ্যা, বেঠিক, কৃত্রিম, নকল' },
  // {
  //   en: 'true',
  //   bn: 'সত্য (Adj.), প্রকৃত (Adj.), আসল (Adj.), ঠিক (Adj.), বাস্তব (Adj.), সাধু (Adj.), বিশ্বস্ত (Adj.), বিশ্বাসী (Adj.), শুদ্ধ (Adj.), বিশুদ্ধ (Adj.), সাঁচা (Adj.), সত্ (Adj.), সাচ্চা (Adj.), নির্ভুল (Adj.), অবিতথ (Adj.), খাঁটি (Adj.), আদত (Adj.), ঋত (Adj.), অকৃত্রিম (Adj.), যথারুপ (Adj.), নমুনাস্বরুপ (Adj.), আন্তরিক (Adj.), অকৈতব (Adj.), আদর্শস্বরূপ (Adj.), উদাহরণস্বরূপ (Adj.), অনুগত (Adj.), যথাবিহিত (Adj.), আস্থাস্থাপনের যোগ্য (Adj.), অটল (Adj.), যথাযথ (Adv.)'
  // },
  { en: 'acrylics', bn: 'এক্রাইলিক' },
  { en: 'agendas', bn: 'বিষয়সূচি' },
  { en: 'abhorrent', bn: 'জঘন্য' },
  { en: 'aboriginals', bn: 'প্রাসঙ্গিক' },
  { en: 'aberrated', bn: 'বিপথগামী হত্তয়া' },
  { en: 'achromatically', bn: 'বর্ণবিকারমুক্তভাবে' },
  { en: 'acuities', bn: 'তীক্ষ্নতা' },
  { en: 'accorded', bn: 'একমত হত্তয়া' },
  { en: 'accentuating', bn: 'স্বরসঙ্ঘাতসহ উচ্চারণ করা' },
  { en: 'accuracies', bn: 'সঠিকতা' },
  { en: 'aislings', bn: 'ছাড়লেও' },
  { en: 'absorbable', bn: 'শোষণযোগ্য' },
  { en: 'abusiveness', bn: 'ছাত্রীরাও তাদের বক্তব্য দিতো' },
  { en: 'aldosterone', bn: 'আলডেসটেরঅন' },
  { en: 'adviser', bn: 'উপদেষ্টা' },
  { en: 'aeronautical', bn: 'বৈমানিক' },
  { en: 'aigrette', bn: 'বকপাখি' },
  { en: 'abolitions', bn: 'রদ' },
  { en: 'adults', bn: 'প্রাপ্তবয়স্কদের' },
  { en: 'acidification', bn: 'অম্লীকরণ' },
  { en: 'acta', bn: 'অ্যাক্টা' },
  { en: 'aisles', bn: 'মিন্টু' },
  { en: 'abysses', bn: 'নরক' },
  { en: 'acquaints', bn: 'পরিচিত করান' },
  { en: 'adonises', bn: 'ভেনাসের প্রণয়পাত্র সুদর্শন যুবাদিশেষ' },
  { en: 'accoutring', bn: 'সজ্জিত করা' },
  { en: 'aerostation', bn: 'বিমানশালা' },
  { en: 'alar', bn: 'পক্ষসম্বন্ধীয়' },
  { en: 'abord', bn: 'নৌরুটে' },
  { en: 'admeasuring', bn: 'ভরণপোষণ করা' },
  { en: 'abdicating', bn: 'ত্যাগ করা' },
  { en: 'abominates', bn: 'ঘৃণায় পরিহার করা' },
  { en: 'adopters', bn: 'গ্রহীতারা' },
  { en: 'adjustment', bn: 'সমন্বয়' },
  { en: 'affines', bn: 'পেজে সম্পর্কিত' },
  { en: 'aerologic', bn: 'বায়বীয়' },
  { en: 'airfield', bn: 'বিমানঘাঁটি' },
  { en: 'accouchement', bn: 'সন্তানপ্রসবার্থ পোয়াতির শয্যায় শয়ন' },
  { en: 'acquittal', bn: 'বেকসুর খালাস' }
]